if(!window.TypekitPreview)window.TypekitPreview={};window.TypekitPreview.config={"pi":"//use.typekit.net/c/{id}/{description}/{format}{/extras*}?{token}","pk":"//use.typekit.net/p/{id}/{description}/{format}{/extras*}?{token}"};
;(function(window,document,undefined){
function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function h(a,b,c){h=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return h.apply(null,arguments)}var ca=Date.now||function(){return+new Date};
function da(a,b){this.ta=a;this.X=b||a;this.O=this.X.document}da.prototype.createElement=function(a,b,c){a=this.O.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.O.createTextNode(c));return a};function ea(a,b,c){a=a.O.getElementsByTagName(b)[0];a||(a=document.documentElement);a.insertBefore(c,a.lastChild)}function fa(a,b){function c(){a.O.body?b():setTimeout(c,0)}c()}
function l(a,b,c){b=b||[];c=c||[];for(var d=a.className.split(/\s+/),e=0;e<b.length;e+=1){for(var f=!1,g=0;g<d.length;g+=1)if(b[e]===d[g]){f=!0;break}f||d.push(b[e])}b=[];for(e=0;e<d.length;e+=1){f=!1;for(g=0;g<c.length;g+=1)if(d[e]===c[g]){f=!0;break}f||b.push(d[e])}a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ga(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1}
function ja(a,b){var c=a.createElement("link",{rel:"stylesheet",href:b,media:"all"}),d=!1;c.onload=function(){d||(d=!0)};c.onerror=function(){d||(d=!0)};ea(a,"head",c)}function ka(a){this.sa=a||"-"}ka.prototype.f=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.sa)};function la(a,b){this.g=a;this.r=a.X.document.documentElement;this.T=b;this.n="wf";this.m=new ka("-");this.ma=!1!==b.events;this.F=!1!==b.classes}
function ma(a){a.F&&l(a.r,[a.m.f(a.n,"loading")]);m(a,"loading")}function p(a){if(a.F){var b=ga(a.r,a.m.f(a.n,"active")),c=[],d=[a.m.f(a.n,"loading")];b||c.push(a.m.f(a.n,"inactive"));l(a.r,c,d)}m(a,"inactive")}function m(a,b,c){if(a.ma&&a.T[b])if(c)a.T[b](c.getName(),r(c));else a.T[b]()}function s(a,b){this.Q=a;this.Z=4;this.R="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.R=c[1],this.Z=parseInt(c[2],10))}s.prototype.getName=function(){return this.Q};function r(a){return a.R+a.Z}
function t(a,b){this.g=a;this.C=b;this.q=this.g.createElement("span",{"aria-hidden":"true"},this.C)}function u(a){ea(a.g,"body",a.q)}
function v(a){var b;b=[];for(var c=a.Q.split(/,\s*/),d=0;d<c.length;d++){var e=c[d].replace(/['"]/g,"");-1==e.indexOf(" ")?b.push(e):b.push("'"+e+"'")}b=b.join(",");c="normal";"o"===a.R?c="oblique":"i"===a.R&&(c="italic");return"display:block;position:absolute;top:-9999px;left:-9999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+b+";"+("font-style:"+c+";font-weight:"+(a.Z+"00")+";")}
t.prototype.remove=function(){var a=this.q;a.parentNode&&a.parentNode.removeChild(a)};
function na(a,b,c,d,e,f,g){this.$=a;this.ra=b;this.g=c;this.t=d;this.C=g||"BESbswy";this.D={};this.Y=e||3E3;this.ha=f||null;this.K=this.J=this.I=this.H=null;this.H=new t(this.g,this.C);this.I=new t(this.g,this.C);this.J=new t(this.g,this.C);this.K=new t(this.g,this.C);a=new s(this.t.getName()+",serif",r(this.t));a=v(a);this.H.q.style.cssText=a;a=new s(this.t.getName()+",sans-serif",r(this.t));a=v(a);this.I.q.style.cssText=a;a=new s("serif",r(this.t));a=v(a);this.J.q.style.cssText=a;a=new s("sans-serif",
r(this.t));a=v(a);this.K.q.style.cssText=a;u(this.H);u(this.I);u(this.J);u(this.K)}var w={Fa:"serif",Ea:"sans-serif"},x=null;function oa(){if(null===x){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent);x=!!a&&(536>parseInt(a[1],10)||536===parseInt(a[1],10)&&11>=parseInt(a[2],10))}return x}na.prototype.start=function(){this.D.serif=this.J.q.offsetWidth;this.D["sans-serif"]=this.K.q.offsetWidth;this.wa=ca();pa(this)};
function qa(a,b,c){for(var d in w)if(w.hasOwnProperty(d)&&b===a.D[w[d]]&&c===a.D[w[d]])return!0;return!1}function pa(a){var b=a.H.q.offsetWidth,c=a.I.q.offsetWidth,d;(d=b===a.D.serif&&c===a.D["sans-serif"])||(d=oa()&&qa(a,b,c));d?ca()-a.wa>=a.Y?oa()&&qa(a,b,c)&&(null===a.ha||a.ha.hasOwnProperty(a.t.getName()))?y(a,a.$):y(a,a.ra):ra(a):y(a,a.$)}function ra(a){setTimeout(h(function(){pa(this)},a),50)}
function y(a,b){setTimeout(h(function(){this.H.remove();this.I.remove();this.J.remove();this.K.remove();b(this.t)},a),0)}function A(a,b,c){this.g=a;this.B=b;this.U=0;this.ka=this.ga=!1;this.Y=c}A.prototype.na=function(a){var b=this.B;b.F&&l(b.r,[b.m.f(b.n,a.getName(),r(a).toString(),"active")],[b.m.f(b.n,a.getName(),r(a).toString(),"loading"),b.m.f(b.n,a.getName(),r(a).toString(),"inactive")]);m(b,"fontactive",a);this.ka=!0;sa(this)};
A.prototype.oa=function(a){var b=this.B;if(b.F){var c=ga(b.r,b.m.f(b.n,a.getName(),r(a).toString(),"active")),d=[],e=[b.m.f(b.n,a.getName(),r(a).toString(),"loading")];c||d.push(b.m.f(b.n,a.getName(),r(a).toString(),"inactive"));l(b.r,d,e)}m(b,"fontinactive",a);sa(this)};function sa(a){0==--a.U&&a.ga&&(a.ka?(a=a.B,a.F&&l(a.r,[a.m.f(a.n,"active")],[a.m.f(a.n,"loading"),a.m.f(a.n,"inactive")]),m(a,"active")):p(a.B))}
function B(a,b,c,d){this.h=null!=a?a:null;this.s=null!=b?b:null;this.L=null!=c?c:null;this.f=null!=d?d:null}var ta=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;B.prototype.compare=function(a){return this.h>a.h||this.h===a.h&&this.s>a.s||this.h===a.h&&this.s===a.s&&this.L>a.L?1:this.h<a.h||this.h===a.h&&this.s<a.s||this.h===a.h&&this.s===a.s&&this.L<a.L?-1:0};function C(a,b){return-1===a.compare(b)}function D(a,b){return 0===a.compare(b)||1===a.compare(b)}
function E(a,b){return 0===a.compare(b)||-1===a.compare(b)}function F(a,b){return 0===a.compare(b)}B.prototype.toString=function(){return[this.h,this.s||"",this.L||"",this.f||""].join("")};function H(a){a=ta.exec(a);var b=null,c=null,d=null,e=null;a&&(null!==a[1]&&a[1]&&(b=parseInt(a[1],10)),null!==a[2]&&a[2]&&(c=parseInt(a[2],10)),null!==a[3]&&a[3]&&(d=parseInt(a[3],10)),null!==a[4]&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new B(b,c,d,e)}
function I(a,b,c,d,e,f,g){this.Q=a;this.p=b;this.A=c;this.w=d;this.e=e;this.c=f;this.V=g}I.prototype.getName=function(){return this.Q};function ua(a,b){this.b=a;this.G=b}var va=new I("Unknown",new B,"Unknown",new B,"Unknown",new B,void 0);
ua.prototype.parse=function(){var a;if(-1!=this.b.indexOf("MSIE")||-1!=this.b.indexOf("Trident/")){a=J(this);var b=H(L(this)),c=null,d=null,e=null,e=M(this.b,/Trident\/([\d\w\.]+)/,1),f=N(this.G),c=-1!=this.b.indexOf("MSIE")?H(M(this.b,/MSIE ([\d\w\.]+)/,1)):H(M(this.b,/rv:([\d\w\.]+)/,1));""!=e?(d="Trident",e=H(e)):(d="Unknown",e=new B);a=new I("MSIE",c,d,e,a,b,f)}else if(-1!=this.b.indexOf("Edge/"))a=J(this),b=H(L(this)),c=H(M(this.b,/Edge\/([\d\w\.]+)/,1)),a=new I("Edge",c,"Edge",c,a,b,N(this.G));
else if(-1!=this.b.indexOf("Opera"))a:if(a="Unknown",b=H(M(this.b,/Presto\/([\d\w\.]+)/,1)),c=H(L(this)),d=N(this.G),null!==b.h?a="Presto":(-1!=this.b.indexOf("Gecko")&&(a="Gecko"),b=H(M(this.b,/rv:([^\)]+)/,1))),-1!=this.b.indexOf("Opera Mini/"))f=H(M(this.b,/Opera Mini\/([\d\.]+)/,1)),a=new I("OperaMini",f,a,b,J(this),c,d);else{if(-1!=this.b.indexOf("Version/")&&(f=H(M(this.b,/Version\/([\d\.]+)/,1)),null!==f.h)){a=new I("Opera",f,a,b,J(this),c,d);break a}f=H(M(this.b,/Opera[\/ ]([\d\.]+)/,1));
a=null!==f.h?new I("Opera",f,a,b,J(this),c,d):new I("Opera",new B,a,b,J(this),c,d)}else/OPR\/[\d.]+/.test(this.b)?a=wa(this):/AppleWeb(K|k)it/.test(this.b)?a=wa(this):-1!=this.b.indexOf("Gecko")?(a="Unknown",b=new B,c=H(L(this)),-1!=this.b.indexOf("Firefox")?(a="Firefox",b=H(M(this.b,/Firefox\/([\d\w\.]+)/,1))):-1!=this.b.indexOf("Mozilla")&&(a="Mozilla"),d=H(M(this.b,/rv:([^\)]+)/,1)),a=new I(a,b,"Gecko",d,J(this),c,N(this.G))):a=va;return a};
function J(a){var b=M(a.b,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=M(a.b,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function L(a){var b=M(a.b,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=M(a.b,/Windows Phone( OS)? ([^;)]+)/,2))||(b=M(a.b,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=M(a.b,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=M(a.b,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function wa(a){var b=J(a),c=H(L(a)),d=H(M(a.b,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),e="Unknown",f=new B,f="Unknown";/OPR\/[\d.]+/.test(a.b)?e="Opera":-1!=a.b.indexOf("Chrome")||-1!=a.b.indexOf("CrMo")||-1!=a.b.indexOf("CriOS")?e="Chrome":/Silk\/\d/.test(a.b)?e="Silk":"BlackBerry"==b||"Android"==b?e="BuiltinBrowser":-1!=a.b.indexOf("PhantomJS")?e="PhantomJS":-1!=a.b.indexOf("Safari")?e="Safari":-1!=a.b.indexOf("AdobeAIR")?e="AdobeAIR":-1!=a.b.indexOf("PlayStation")&&(e="BuiltinBrowser");"BuiltinBrowser"==
e?f="Unknown":"Silk"==e?f=M(a.b,/Silk\/([\d\._]+)/,1):"Chrome"==e?f=M(a.b,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.b.indexOf("Version/")?f=M(a.b,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==e?f=M(a.b,/AdobeAIR\/([\d\.]+)/,1):"Opera"==e?f=M(a.b,/OPR\/([\d.]+)/,1):"PhantomJS"==e&&(f=M(a.b,/PhantomJS\/([\d.]+)/,1));f=H(f);return new I(e,f,"AppleWebKit",d,b,c,N(a.G))}function M(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function N(a){if(a.documentMode)return a.documentMode}function O(a){this.g=a}
O.prototype.toString=function(){var a=this.g;return encodeURIComponent(a.X.location.hostname||a.ta.location.hostname)};function xa(a,b){this.o=a;this.ba=b}xa.prototype.toString=function(){for(var a=[],b=0;b<this.ba.length;b++)for(var c=this.ba[b],d=c.u(),c=c.u(this.o),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=!0;break a}f=!1}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)b.unshift(parseInt(a.slice(0>d-4?0:d-4,d),2).toString(16));return b.join("")};
function ya(a){this.ya=a}ya.prototype.f=function(a,b){var c=a||{},d=this.ya.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(b?"http:":"https:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function za(a,b,c,d,e){for(var f=[],g=0;g<d.length;g++)f.push(d[g].toString());c={format:c,extras:f};c.id=a;c.description=b;e&&(c.token=e);return c}function Aa(a,b,c,d,e){this.v=a;this.P=b;this.qa=c;this.xa=d;this.ua=e;this.da={};this.W={}}
Aa.prototype.u=function(a){return a?(this.da[a]||this.P).slice(0):this.P.slice(0)};function Ba(a,b,c){for(var d=[],e=a.v.split(",")[0].replace(/"|'/g,""),f=a.u(),g,k=[],q={},n=0;n<f.length;n++)g=f[n],0<g.length&&!q[g]&&(q[g]=!0,k.push(g));c=c.ja?c.ja(e,k,d):k;a.da[b]=c;a.W[b]=d}function Ca(a,b){for(var c=a.u(b),d=a.W[b]||[],e=[],f=0;f<c.length;f++)e.push(new s(a.v,c[f]));for(f=0;f<d.length;f++)if(c=d[f].v,c!==a.v)for(var g=d[f].u(),k=0;k<g.length;k++)e.push(new s(c,g[k]));return e}
function Da(a,b){this.v=a;this.P=b}Da.prototype.u=function(){return this.P};function Ea(){this.la=this.za=this.M=this.ea=this.fa=!0}function P(a){return"Windows"===a.e}function Q(a){return P(a)&&D(a.c,new B(6,1))}function R(a){return P(a)&&F(a.c,new B(5,1))||P(a)&&F(a.c,new B(5,2))||P(a)&&F(a.c,new B(6,0))||Q(a)}function S(a){return"Macintosh"===a.e&&(D(a.c,new B(10,4))||null===a.c.h)}function T(a,b){return b.fa&&("iPhone"===a.e||"iPod"===a.e)&&D(a.c,new B(4,2))&&C(a.c,new B(5))}
function Fa(a,b){return b.fa&&("iPhone"===a.e||"iPod"===a.e)&&D(a.c,new B(5))}function Ga(a,b){return b.ea&&"iPad"===a.e&&D(a.c,new B(4,2))&&C(a.c,new B(5))}function Ha(a,b){return b.ea&&"iPad"===a.e&&D(a.c,new B(5))}function U(a,b){return b.M&&"Android"===a.e}function Ia(a,b){return U(a,b)&&D(a.c,new B(2,2))&&C(a.c,new B(3,1))}function Ja(a,b){return U(a,b)&&D(a.c,new B(3,1))&&C(a.c,new B(4,1))}function V(a){return"Linux"===a.e||"Ubuntu"===a.e}
function Ka(a){return"Safari"===a.getName()&&"AppleWebKit"===a.A||"Unknown"===a.getName()&&"AppleWebKit"===a.A&&("iPhone"===a.e||"iPad"===a.e||"iPod"===a.e)}function La(a){return"Chrome"===a.getName()&&D(a.p,new B(6))&&E(a.p,new B(35))}function Ma(a){return"Chrome"===a.getName()&&D(a.p,new B(36))}function Na(a){return"BuiltinBrowser"===a.getName()}function Oa(a){this.ja=a}function Pa(a,b){return b}
var W={Ca:"a",Ha:"d",Ba:"i",Da:"j",Aa:"k",Ga:"l",NONE:"x"},X={a:function(a,b){return"Safari"===a.getName()&&"AppleWebKit"===a.A&&D(a.w,new B(525,13))&&C(a.w,new B(534,50))&&(R(a)||S(a))||Na(a)&&(Ia(a,b)||U(a,b)&&D(a.c,new B(4,1)))||b.M&&"Silk"===a.getName()&&C(a.p,new B(2))&&(Ia(a,b)||S)||b.M&&"Silk"===a.getName()&&D(a.p,new B(2))&&U(a,b)&&D(a.c,new B(4,1))||Ka(a)&&(Ga(a,b)||T(a,b))||La(a)&&(Ga(a,b)||T(a,b))||Ma(a)&&(Ga(a,b)||T(a,b))||"AdobeAIR"===a.getName()&&D(a.p,new B(2,5))&&(P(a)&&null===a.c.h||
V(a)||S(a))},d:function(a,b){var c;(c=La(a)&&(R(a)||V(a)||S(a)||U(a,b)||"CrOS"===a.e||"CrKey"===a.e||Ha(a,b)||Fa(a,b))||Ma(a)&&(Ha(a,b)||Fa(a,b)))||(c="Gecko"===a.A&&1===a.w.compare(new B(1,9,1))&&E(a.w,new B(38))&&(R(a)||V(a)||S(a)||U(a,b)));(c=c||"Safari"===a.getName()&&"AppleWebKit"===a.A&&D(a.w,new B(534,50))&&(R(a)||S(a))||Ka(a)&&(Ha(a,b)||Fa(a,b)))||(c="Opera"===a.getName()&&D(a.p,new B(11,10))&&E(a.p,new B(22))&&(R(a)||V(a)||S(a)||U(a,b)));return c||"MSIE"===a.getName()&&9<=a.V&&(Q(a)||P(a)&&
F(a.c,new B(6,0)))||"Edge"===a.getName()&&Q(a)||"MSIE"===a.getName()&&b.za&&"Windows Phone"===a.e&&D(a.c,new B(8))||Na(a)&&(b.la&&"BlackBerry"===a.e&&D(a.c,new B(10))||V(a))},j:function(a,b){return Na(a)&&Ja(a,b)||b.M&&"Silk"===a.getName()&&D(a.p,new B(2))&&(Ja(a,b)||V(a))},i:function(a){return"MSIE"===a.getName()&&D(a.p,new B(6,0))&&(void 0===a.V||9>a.V)&&R(a)},l:function(a,b){return Ma(a)&&(R(a)||V(a)||S(a)||U(a,b)||"CrOS"===a.e||"CrKey"===a.e)||"Gecko"===a.A&&D(a.w,new B(39))&&(R(a)||V(a)||S(a)||
U(a,b))||"Opera"===a.getName()&&D(a.p,new B(23))&&(R(a)||V(a)||S(a)||U(a,b))},x:function(){return!1}};function Qa(){var a=Ra,b=new Ea,c=new Ea||b,d;for(d in W){var e=W[d];if(X[e]&&X[e](a,c))return e}for(d in W)if(e=W[d],X[e]&&X[e](a,b))return"x";return"k"}var Sa={};
Sa.i=new Oa(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f;f=e;f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+f;c.push(new Da(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++){f=c[e];for(var g=0;g<f.length;g++){var k=f[g];if(a[k]){d=d.concat(a[k]);break}}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=!0,a.push(f));c=[];for(d=0;d<b.length;d++)for(e=b[d],f=0;f<a.length;f++)g=a[f],
g==e&&c.push(g);return c});var Y={};Y.a=Y.d=Y.l=Y.j=function(){return[]};Y.i=function(a,b,c){return[new O(a),new xa(b,c)]};Y.k=function(a){return[new O(a)]};var Ta={all:1,"default":2};function Ua(a){var b=[];a.length&&b.push("1w");for(var c=0;c<a.length;c++){var d=a[c],e=[];e.push(d.css_name);e.push(d.id);var f=d.primer;f&&64===f.length?e.push(d.primer):e.push(Ta[d.subset]);for(f=0;f<d.variations.length;f++)e.push(d.variations[f]);b.push(e.join(","))}return b.join(";")}
function Z(a,b,c,d,e,f,g){this.ia=a;this.o=c;this.ca=d;this.g=e;this.b=f;this.r=g;this.N="anonymous";this.S=null;this.aa="default"}Z.prototype.va=function(a){var b=a.auth_id;b&&(this.N=b);if(b=a.auth_token)this.S=b;(a=a.default_subset)&&Ta[a]&&(this.aa=a)};Z.prototype.pa=function(a){var b=null;if("be"!==this.N)return null;a=Va(this,a);var c=Wa(a);if("x"!==this.o){for(b=0;b<c.length;b++)Ba(c[b],this.o,this.ca);a=Ua(a);b=this.o;c=Y[b](this.g,b,c);c=za(this.N,a,this.o,c,this.S||void 0);b=this.ia.f(c)}return b};
Z.prototype.load=function(a,b){var c=b||{};a=Va(this,a);var d=Wa(a),e=null;if("x"!==this.o){for(e=0;e<d.length;e++)Ba(d[e],this.o,this.ca);var e=Ua(a),f;f=this.o;f=Y[f](this.g,f,d);e=za(this.N,e,this.o,f,this.S||void 0);e=this.ia.f(e)}if(Xa(this,d,e,c)){c=[];for(e=0;e<d.length;e++){var g=d[e],k=g.u(this.o);f=g.qa;var q=g.xa,n=g.ua;0<k.length&&c.push(Ya(f,k,g.v,q,n));g=g.W[this.o]||[];for(k=0;k<g.length;k++){var G=g[k];c.push(Ya(f,G.u(),G.v,q,n))}}d=c}else d=[];return d};
function Xa(a,b,c,d){var e=!1!==d.events,f=!1!==d.classes,g=new la(a.g,d);if("x"===a.o)return p(g),!1;if(b.length){var k=[],q={},n=new A(a.g,g,d.timeout);for(d=0;d<b.length;d++)k=k.concat(Ca(b[d],a.o));for(d=0;d<k.length;d++)q[k[d].getName()]="BESbswy\ue000\ue001\ue002\ue003\ue004\ue005\ue006";ma(g);ja(a.g,c);(f||e)&&fa(a.g,function(){var a=k,b={},c=q||{};if(0===a.length)p(n.B);else{n.U+=a.length;n.ga=!0;var d,e=[];for(d=0;d<a.length;d++){var f=a[d],g=c[f.getName()],z=n.B,ia=f;z.F&&l(z.r,[z.m.f(z.n,
ia.getName(),r(ia).toString(),"loading")]);m(z,"fontloading",ia);z=null;z=new na(h(n.na,n),h(n.oa,n),n.g,f,n.Y,b,g);e.push(z)}for(d=0;d<e.length;d++)e[d].start()}})}return!0}
function Va(a,b){for(var c=[],d=0;d<b.length;d++){var e=/^[A-Za-z0-9_-]+$/,f=b[d],g=f.id,k=f.variations,q=f.css_name,q=q&&"string"==typeof q&&q.match(e)?q:g,n=f.subset,n=Ta[n]?n:a.aa,f=(f=f.primer)&&64===f.length?f:null;if("string"==typeof g&&g.match(e)&&"object"==typeof k&&0<k.length){for(var e={},G=[],ha=0;ha<k.length;ha++){var K=k[ha];K&&0<K.length&&!e[K]&&(G.push(K),e[K]=!0)}0<G.length&&c.push(Ya(g,G.sort(),q,n,f))}}return c.sort(function(a,b){var c=a.css_name,d=b.css_name;return c<d?-1:c>d?1:
0})}function Wa(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(new Aa(d.css_name,d.variations,d.id,d.subset,d.primer))}return b}function Ya(a,b,c,d,e){return{id:a,variations:b,css_name:c,subset:d,primer:e}}window.TypekitPreview||(window.TypekitPreview={});
if(!window.TypekitPreview.load){var Za=new ya((window.TypekitPreview.config||{}).pk),Ra=(new ua(navigator.userAgent,document)).parse(),$a=Qa(),$=new Z(Za,0,$a,Sa[$a]||new Oa(Pa),new da(window),Ra,document.documentElement);window.TypekitPreview=$;window.TypekitPreview.setup=$.va;window.TypekitPreview.load=$.load;window.TypekitPreview.getCssUrl=$.pa};
})(this,document);
